### ISSUE TITLE
OpenPolicy not used as described in docs

### ISSUE THREAD

**Issue by Minirogue** [Kodein-Framework/Kodein-DB#10]
In [the documentation](https://docs.kodein.org/kodein-db/0.2.0/core/setup-database.html), it says a database can be opened with different open policies by using
``` kotlin
val db = DB.open("path/to/db", LevelDB.OpenPolicy.OPEN)
```

However the second argument of `DB.open()` is `vararg options: Options.Open`. I can't seem to track down any usages of the `Options.Open` interface, so it's unclear what the intended usage is supposed to be.

**Comment by SalomonBrys** [comment]
The correct way is `LevelDBOptions.OpenPolicy(LevelDB.OpenPolicy.CREATE)`, which is absolutely not easy or discoverable.
The next version will add a utility to make this parameter a lot easier (and I'll update the doc, of course).

**Comment by SalomonBrys** [comment]
Version `0.3.0-beta` provides a new [`OpenPolicy`](https://github.com/Kodein-Framework/Kodein-DB/blob/master/kdb/kodein-db-api/src/commonMain/kotlin/org/kodein/db/OpenPolicy.kt) object that contains `Open`, `OpenOrCreatre` and `Create`.
The [setup documentation](https://docs.kodein.org/kodein-db/0.3.0/core/setup-database.html#_open_statement) has been updated to show this new API.

Thanks for the report !
