### ISSUE TITLE
No `models()` function for Cursor

### ISSUE THREAD

**Issue by Minirogue** [Kodein-Framework/Kodein-DB#13]
In [the docs](https://docs.kodein.org/kodein-db/0.2.0/core/operations.html) under **Using a cursor** and **As a sequence** there are several code blocks that use `Cursor.models()`, such as 
```kotlin
db.find<User>().byIndex("lastName", "Doe").models().forEach {
    println(it)
}
``` 
However, it doesn't appear that this function exists. One can get what I believe are the intended results of `.models()` with `.useModels { it }`.

**Comment by SalomonBrys** [comment]
Indeed, this was changed before release, and I should be ashamed to have forgotten to update the doc.
Thanks for the report ;)

**Comment by SalomonBrys** [comment]
Version `0.3.0-beta` provides a new API to transform cursors into sequences, and the [cursor documentation](https://docs.kodein.org/kodein-db/0.3.0/core/iteration.html#_as_a_sequence) has been updated to show both `as*Sequence` and `use*` APIs.

Thanks for the report !
