### ISSUE TITLE
kodein-leveldb-jni-macos not published

### ISSUE THREAD

**Issue by jmfayard** [Kodein-Framework/Kodein-DB#14]
Hello I tried kodein-db here 
https://github.com/LouisCAD/kotlin-libraries-playground/commit/9165f6ecfc148a2d42335bd8b7cb6fbc951cc538

I noted an error in the doc. It talks about @Index  but it seems to be @Indexed here
https://docs.kodein.org/kodein-db/0.2.0/core/defining-data-model.html

My main problem is that my program fails on a mac with 
> Caused by: java.lang.IllegalStateException: Could not load kodein-leveldb-jni-macos. Have you added it to the classpath?

The thing is `kodein-leveldb-jni-linux` has been published there, but not `kodein-leveldb-jni-macos` (or windows for that matter)

https://dl.bintray.com/kodein-framework/Kodein-DB/org/kodein/db/

**Comment by SalomonBrys** [comment]
During development, we disabled the macos target as it took too long to compile.
We still need to re-enable it. It'll be done this week. I'll post here when it is available.
Sorry for the delay ;)

Also, the Windows target suddently failed to compile on Github Actions, so we need to investigate that as well.

**Comment by LouisCAD** [comment]
@SalomonBrys I released the last version of Splitties for Kotlin 1.4 via GitHub Actions successfully (after lots of trial and errors) for a bunch of targets including macOS and Windows. Let me know if I can be of any help investigating and getting a reliable release process for you.

**Comment by SalomonBrys** [comment]
Version [0.4.0`](https://github.com/Kodein-Framework/Kodein-DB/releases/tag/0.4.0-beta) has been published.

With this version, the three artefacts `kodein-db-jni-jvm-linux`, `kodein-db-jni-jvm-macos` and `kodein-db-jni-jvm-windows` are [released in Bintray](https://bintray.com/kodein-framework/Kodein-DB/kodein-leveldb-jni-jvm).
