### ISSUE TITLE
Under no circumstances should it be used in a server!?

### ISSUE THREAD

**Issue by mahdisml** [Kodein-Framework/Kodein-DB#19]
`CAUTION: Under no circumstances should it be used in a server!`

Why ?

**Comment by CarlosEsco** [comment]
It was mentioned in the intial video at KotlinConf https://www.youtube.com/watch?v=2mpzbFxUkAE&feature=youtu.be
TL/DW: Performance won't stack up for something designed for a server

**Comment by SalomonBrys** [comment]
Thast's correct.

- There's an **object cache**, which is very useful for a client (gives huge performance benefits, and allows the DB to be used as an event bus). On a server, this cache would very quickly clog up the memory and be of little use to a server.
- There's a **locking mechanism** that locks the DB on each write. ensures multi-thread synchronization with the object-cache as well as index synchronized updates (ensuring that, if you would to update the same key using two object in two different threads, the indices would always reflect the correct latest value for that key). While this is not a problem for clients (you would need a *lot* of read and writes in a *lot* of threads to see a perf loss), a server handling a decent amount of query per seconds would probably be beside any server-oriented DB.
- There's no mechanisms in place for **scaling, sharding, or replicating**, which are important for server DBs as soon as your app starts to scale.

All in all, Kodein-DB is thought with clients in mind. It would of course work on a server, but would offer poor performance, over memory consumption & no scaling capabilities.
