### ISSUE TITLE
[ASK] It's viable use the kodein-DB on minecraft server game?

### ISSUE THREAD

**Issue by Katekko** [Kodein-Framework/Kodein-DB#23]
Today it's possible to create a server of minecraft using KOTLIN.
I'm wondering if you recommend use koden-db instead sqlite... It's really more easy use the kodein instead sqlite to save data of the users and update

**Comment by romainbsl** [comment]
We don't : https://docs.kodein.org/kodein-db/0.4/index.html

> Under no circumstances should it be used in a server!

Also, see https://github.com/Kodein-Framework/Kodein-DB/issues/19
