### ISSUE TITLE
Flush a table content

### ISSUE THREAD

**Issue by ggimes** [Kodein-Framework/Kodein-DB#26]
Hi, 

I'm trying to figure out how to flush the content of a table and I couldn't find the answer in the documentation.
Is there an equivalent to:

```
localDB.deleteAll<SomeModelClass>()
```

Tried
```
localDB.delete(localDB.find<SomeModelClass>().all().key())
```
Get the error `java.lang.IllegalStateException: Cursor is not valid`

**Comment by SalomonBrys** [comment]
The `delete` function expects the id of the model you want to delete.
Here is a simple function that does what you want:

```
public inline fun <reified M : Any> DB.deleteAll() {
    find<M>().all().useKeys { seq -> 
        seq.forEach { delete(it) }
    }
}
```

I'll leave this issue open to integrate it in the library.

**Comment by SalomonBrys** [comment]
The newest version (0.6.0) offers the `deleteAll` API that can be used as such:

```
db.deleteAll(db.find<SomeModelClass>().all())
```
