### ISSUE TITLE
Kotlinx Serialization incompatibility when using Ktor

### ISSUE THREAD

**Issue by joreilly** [Kodein-Framework/Kodein-DB#27]
When using following versions

```
    const val kotlin = "1.4.30"
    const val kotlinCoroutines = "1.4.3-native-mt"
    const val ktor = "1.5.2"
    const val kotlinxSerialization = "1.0.1"
    const val kodein_db = "0.6.0-beta"
```

I'm getting following when building iOS app.  Are there any known combinations of versions that will allow `0.6.0-beta` to work with Ktor atm?

```Unbound public symbol for public kotlinx.serialization.json/JsonDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.json/JsonDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.json/JsonDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.json/JsonDecoder.decodeSerializableElement|8042733237355806987[0]
Unbound public symbol for public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.json.internal/StreamingJsonDecoder.decodeSerializableElement|8042733237355806987[0]
Unbound public symbol for public kotlinx.serialization.internal/NamedValueDecoder.decodeNullableSerializableElement|7091057077819363828[0] public kotlinx.serialization.internal/NamedValueDecoder.decodeNullableSerializableElement|7091057077819363828[0]
Unbound public symbol for public kotlinx.serialization.internal/NamedValueDecoder.decodeSerializableElement|8042733237355806987[0] public kotlinx.serialization.internal/NamedValueDecoder.decodeSerializableElement|8042733237355806987[0]
```

**Comment by joreilly** [comment]
I should add this is a Kotlin Multiplatform application and is using `org.kodein.db:kodein-db-serializer-kotlinx` dependency.

**Comment by joreilly** [comment]
Pushed updates I made to following branch https://github.com/joreilly/BikeShare/tree/kotlin_1_4_30

**Comment by SalomonBrys** [comment]
Hi @joreilly, Kodein-DB 0.6.0-beta uses KotlinX.Serialization version `1.1.0`.
However, it seems that Ktor still uses `1.0.1`. I gues the problem comes from there...

**Comment by SalomonBrys** [comment]
Here is the issue in Ktor that tracks update to Kx.Serializarion 1.1.0: https://youtrack.jetbrains.com/issue/KTOR-2238

**Comment by SalomonBrys** [comment]
@joreilly can you try version [`0.6.0-beta-kx.ser-1.0.1-126-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/org/kodein/db/kodein-db/0.6.0-beta-kx.ser-1.0.1-126-SNAPSHOT/)?
It's basically version `0.6.0` but with KotinX.Serialization reverted to `1.0.1`.
You'll need to add the Sonatype OSS Snapshots repository to your project:

```
repositories {
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
}
```

**Comment by joreilly** [comment]
Just tried that out and not seeing that error now!

**Comment by joreilly** [comment]
Hopefully there'll be version of ktor soon that works with 1.1.0......will use this snapshot version anyway in the meantime.

**Comment by joreilly** [comment]
Ktor 1.5.3 was released short while ago so have been able to update ehttps://github.com/joreilly/BikeShare to that, Kotlinx Serialization 1.10 and, as a result, latest Kodein-db beta.
