### ISSUE TITLE
How can I use this lib?

### ISSUE THREAD

**Issue by Katekko** [Kodein-Framework/Kodein-DB#3]
Is there a DEMO or a tutorial to follow? Or a just simple documentation? I really need use this

I'm working with minecraft's plugins and writing some kotlins code. I need store my data localy, but I dont wanna use SQLite since that I saw that lib. I just wanna know how to start, please.

**Comment by AlexTrotsenko** [comment]
I see, that initial docs are added in https://github.com/Kodein-Framework/Kodein-DB/commit/fa71b2ebfe4a224d620dbbc2240b68007456fa09

But the same time some essential information like Gradle set-up is still missing. 
Perhaps example app in this repo could help.

**Comment by SalomonBrys** [comment]
Lib has (finally) been released, and its install documentation is here : https://docs.kodein.org/kodein-db/0.2.0/core/install.html
