### ISSUE TITLE
Data filtering feature

### ISSUE THREAD

**Issue by AronMitk** [Kodein-Framework/Kodein-DB#31]
Is there any plans to have data filtering with all these: greater than, equal, etc...?

For example:
db.find<User>().where(x -> x.Eq("ID", "value"))

**Comment by SalomonBrys** [comment]
Not in the query DSL, but you can easily implement this with sequences:

```kotlin
db.find<User>().all().use {
    it.asModelSequence()
        .filter { it.age >= 30 }
        .forEach {
            println(it)
        }
}
```
