### ISSUE TITLE
Automatic indexes generation in KMM

### ISSUE THREAD

**Issue by AronMitk** [Kodein-Framework/Kodein-DB#32]
I have a simple data class, which I am using in the KMM shared module. Is there are any ways to add indexes without writing an override method?
 Also, are there any plans to implement automatic index generation? That every value will have an index?

```
@Serializable
    data class Testingas(
        override var id : String,
        var title : String
    ) : Metadata{
        override fun indexes() = mapOf("title" to listOf(title))
    }
```

**Comment by SalomonBrys** [comment]
No, at the moment, you need the method.
When compiler plugins become stable, we'll use them for automatic index generation.
