### ISSUE TITLE
Tools needed to build Kodein-DB

### ISSUE THREAD

**Issue by romainbsl** [Kodein-Framework/Kodein-DB#5]
## Listing everything that needs to be done before releasing **Kodein-DB**.

1. crc32c
2. ios-cmake
3. leveldb
4. leveldb-kodein
5. snappy

## Questions?

1. Do we need to build each of those tools?
2. Do we need to build those tools for each platform?
3. For each tool what do we need to run? Thus what compilation tools do we need?

**Comment by SalomonBrys** [comment]
Gradle is configured to build everything for you.

Don't forget to `git submodule update --init` when you checkout the repo !

What you need on the build system is:

- Java 11+
- A javah binary (usualy installed with Java 8) with its path defined in `gradle.properties`: `javah=/usr/bin/javah`
- CLang
- CMake

Note that gradle will first build crc32c & snappy, then leveldb using these two libs, then Kodein-DB.

Note also that each libs has to be recompiled for each targetted platform, so it can take a while.
