### ISSUE TITLE
Is there a way to create an in-memory db for testing?

### ISSUE THREAD

**Issue by CarsonRedeye** [Kodein-Framework/Kodein-DB#9]

**Comment by SalomonBrys** [comment]
No, there's not, and [LevelDB does not support it](https://github.com/dain/leveldb/issues/79).
I suppose providing a Kotlin-only in-memory implementation of the [LevelDB interface](https://github.com/Kodein-Framework/Kodein-DB/blob/master/ldb/kodein-leveldb-api/src/commonMain/kotlin/org/kodein/db/leveldb/LevelDB.kt) using Kotlin Collections wouldn't be very hard.
However, the performances in large dataset would probably be horendous.
If used only for testing, I believe that would be acceptable.
What are your thoughts ?

**Comment by CarsonRedeye** [comment]
Yes I think it would be acceptable. I think it would be quite valuable

**Comment by SalomonBrys** [comment]
Version [0.4.0](https://github.com/Kodein-Framework/Kodein-DB/releases/tag/0.4.0-beta) has been published.

This version includes the new [in-memory test backend](https://docs.kodein.org/kodein-db/0.4/core/tests.html) which you can use to write test without any access to filesystem.

Please let me know if this fits your needs ;)

**Comment by CarsonRedeye** [comment]
Awesome I'll check it out

**Comment by andrejordan** [comment]
Thanks for working on this guys! Really appreciated
